### ISSUE TITLE
Error while try to publish the config

### ISSUE THREAD

**Issue by reypm** [ignited/laravel-omnipay#10]
I followed any step on the README but at this point, when I run the command:

```
php artisan config:publish ignited/laravel-omnipay
```

I got all this errors on console: 

> PHP Fatal error:  Call to undefined method
> Monolog\Logger::toMonologLevel() in
> /var/www/html/alomicuba/plugins/flynsarmy/debugbar/vendor/monolog/monolog/src/Monolog/Handler/AbstractHandler.php
> on line 126 PHP Stack trace: PHP   1. {main}()
> /var/www/html/alomicuba/artisan:0 PHP   2.
> Illuminate\Console\Application::start()
> /var/www/html/alomicuba/artisan:46 PHP   3.
> Illuminate\Console\Application::make()
> /var/www/html/alomicuba/plugins/flynsarmy/debugbar/vendor/laravel/framework/src/Illuminate/Console/Application.php:33
> PHP   4. Illuminate\Foundation\Application->boot()
> /var/www/html/alomicuba/plugins/flynsarmy/debugbar/vendor/laravel/framework/src/Illuminate/Console/Application.php:44
> PHP   5. Illuminate\Foundation\Application->bootApplication()
> /var/www/html/alomicuba/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:589
> PHP   6. Illuminate\Foundation\Application->fireAppCallbacks()
> /var/www/html/alomicuba/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:606
> PHP   7.
> call_user_func:{/var/www/html/alomicuba/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:832}()
> /var/www/html/alomicuba/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:832
> PHP   8.
> {closure:/var/www/html/alomicuba/vendor/laravel/framework/src/Illuminate/Foundation/start.php:223-271}()
> /var/www/html/alomicuba/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:832
> PHP   9. require()
> /var/www/html/alomicuba/vendor/laravel/framework/src/Illuminate/Foundation/start.php:239
> PHP  10. Illuminate\Support\Facades\Log::useFiles()
> /var/www/html/alomicuba/app/start/global.php:34 PHP  11.
> Illuminate\Support\Facades\Facade::__callStatic()
> /var/www/html/alomicuba/app/start/global.php:34 PHP  12.
> Illuminate\Log\Writer->useFiles()
> /var/www/html/alomicuba/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:208
> PHP  13. Monolog\Handler\StreamHandler->__construct()
> /var/www/html/alomicuba/vendor/laravel/framework/src/Illuminate/Log/Writer.php:90
> PHP  14. Monolog\Handler\AbstractHandler->__construct()
> /var/www/html/alomicuba/plugins/flynsarmy/debugbar/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:42
> PHP  15. Monolog\Handler\AbstractHandler->setLevel()
> /var/www/html/alomicuba/plugins/flynsarmy/debugbar/vendor/monolog/monolog/src/Monolog/Handler/AbstractHandler.php:40
> {"error":{"type":"Symfony\Component\Debug\Exception\FatalErrorException","message":"Call
> to undefined method
> Monolog\Logger::toMonologLevel()","file":"\/var\/www\/html\/alomicuba\/plugins\/flynsarmy\/debugbar\/vendor\/monolog\/monolog\/src\/Monolog\/Handler\/AbstractHandler.php","line":126}}

Any advice?

**Comment by PV-Patrick** [comment]
I'm having the same issue.

**Comment by danhunsaker** [comment]
Looks like a broken MonoLog install.  Try running `composer update` first.
