### ISSUE TITLE
Please can you help with some documentation on how we can configure the paypal express checkout?

### ISSUE THREAD

**Issue by AchoArnold** [ignited/laravel-omnipay#13]
I would like to customise the Paypal Express checkout such that it shows the `HeaderImageUrl` of my site and the `ladingPage` URL as seen here https://github.com/ignited/laravel-omnipay/blob/master/src/config/config.php

**Comment by isneezy** [comment]
I answered another question witch leads to the solution of your problem
https://github.com/ignited/laravel-omnipay/issues/15#issuecomment-235526593
