### ISSUE TITLE
Authorize.net issue

### ISSUE THREAD

**Issue by VerzatileTom** [ignited/laravel-omnipay#14]
Hi, I'm having trouble with authorize. After submitting my billing information, authorize response with error saying:

```
  An error occurred while trying to report this transaction to the merchant. An e-mail has been 
  sent to the merchant informing them of the error. The following is the result of the attempt 
  to charge your credit card.

  This transaction has been approved.

  It is advisable for you to contact the merchant to verify that you will receive the product or 
  service.
```

I checked my paramaters and return urls, and i think they're fine.
Hope you can help me with this. Thanks!

**Comment by alexw23** [comment]
This is unrelated to this package, see either a) https://github.com/thephpleague/omnipay-authorizenet or b) speak to authorize net directly.
