### ISSUE TITLE
 BadMethodCallException in LaravelOmnipayManager.php line 129

### ISSUE THREAD

**Issue by obonyojimmy** [ignited/laravel-omnipay#17]
There seems to be abug here : BadMethodCallException in LaravelOmnipayManager.php line 129:
Method [create] is not supported by the gateway [paypal]. using laravel version 5.1

**Comment by trong291990** [comment]
Did you call " Omnipay::create('Paypal_Express') " ?

let use Omnipay::geteway('paypal');
check the config file : 
`<?php

return [

	// The default gateway to use
	'default' => 'paypal',

	// Add in each gateway here
	'gateways' => [
		'paypal' => [
			'driver'  => 'PayPal_Express',
			'options' => [
				'solutionType'   => '',
				'landingPage'    => '',
				'headerImageUrl' => ''
			]
		]
	]

];`

**Comment by alexw23** [comment]
There's a paypal express example here:

https://github.com/ignited/laravel-omnipay#paypal-express-example
