### ISSUE TITLE
Invalid Token

### ISSUE THREAD

**Issue by mitajunior** [ignited/laravel-omnipay#21]
Am trying to do a paypal checkout using this package...i get this after redirect
## success url

http://smstroll.app/billing/checkout/success?token=EC-7TK3635026596924C&PayerID=WTC6UGLBLM7RL
## response

array:9 [▼
  "TIMESTAMP" => "2016-02-15T08:54:18Z"
  "CORRELATIONID" => "30532d497cc6"
  "ACK" => "Failure"
  "VERSION" => "119.0"
  "BUILD" => "18308778"
  "L_ERRORCODE0" => "10410"
  "L_SHORTMESSAGE0" => "Invalid token"
  "L_LONGMESSAGE0" => "Invalid token."
  "L_SEVERITYCODE0" => "Error"
]

What could be the problem?

**Comment by ShemJ** [comment]
i have the same problem

**Comment by alexw23** [comment]
Given this package is just a wrapper around omnipay, post an issue directly on the relevant wrapper for that package. 

I.e for paypal - https://github.com/thephpleague/omnipay-paypal
