### ISSUE TITLE
require error

### ISSUE THREAD

**Issue by klgd** [ignited/laravel-omnipay#22]
I require omnipay in my porject (laravel5.2),but it wrong

` Problem 1
- Installation request for ignited/laravel-omnipay ^2.1 -> satisfiable by ignited/laravel-omnipay[2.1.0].
- Conclusion: remove symfony/http-foundation v3.0.2
- Conclusion: don't install symfony/http-foundation v3.0.2
- ignited/laravel-omnipay 2.1.0 requires omnipay/common 2.3.\* -> satisfiable by omnipay/common[2.3.2, v2.3.0, v2.3.1,
  v2.3.3, v2.3.4].
  .............
  - Can only install one of: symfony/http-foundation[v2.6.9, v3.0.2].
  - Can only install one of: symfony/http-foundation[v2.7.0, v3.0.2].
  - Can only install one of: symfony/http-foundation[v2.7.1, v3.0.2].
  - Can only install one of: symfony/http-foundation[v2.7.2, v3.0.2].
  - Can only install one of: symfony/http-foundation[v2.7.3, v3.0.2].
  - Can only install one of: symfony/http-foundation[v2.7.4, v3.0.2].
  - Can only install one of: symfony/http-foundation[v2.7.5, v3.0.2].
  - Can only install one of: symfony/http-foundation[v2.7.6, v3.0.2].
  - Can only install one of: symfony/http-foundation[v2.7.7, v3.0.2].
  - Can only install one of: symfony/http-foundation[v2.7.8, v3.0.2].
  - Can only install one of: symfony/http-foundation[v2.7.9, v3.0.2].
  - Installation request for symfony/http-foundation == 3.0.2.0 -> satisfiable by symfony/http-foundation[v3.0.2].
    `

how can i do it?

**Comment by moiroca** [comment]
What is the status of this issue? I'm having this issue also.

**Comment by alexw23** [comment]
What's your composer.json file look like?

**Comment by moiroca** [comment]
My composer is the composer.json of a fresh laravel 5.2 installation.

{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.2.*"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~4.0",
        "symfony/css-selector": "2.8.*|3.0.*",
        "symfony/dom-crawler": "2.8.*|3.0.*"
    },
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "classmap": [
            "tests/TestCase.php"
        ]
    },
    "scripts": {
        "post-root-package-install": [
            "php -r \"copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ],
        "post-install-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postInstall",
            "php artisan optimize"
        ],
        "post-update-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postUpdate",
            "php artisan optimize"
        ]
    },
    "config": {
        "preferred-install": "dist"
    }
}

**Comment by alexw23** [comment]
Is this issue still happening?
