### ISSUE TITLE
Class '\Omnipay\PayPal\ExpressGateway' not found lol

### ISSUE THREAD

**Issue by soly2014** [ignited/laravel-omnipay#25]

**Comment by kevindierkx** [comment]
You receive this message when the package defaults to it's default payment provider. Make sure you publish the config and change the driver to whatever you please. (Also make sure you required the correct driver dependencies like `omnipay/mollie` in your composer.json)

A correct config would look something like the following:
```
<?php

return [
    'default' => 'mollie',

    'gateways' => [
        'mollie' => [
            'driver' => 'Mollie',
            'options' => [
                'apiKey' => getenv('MOLLIE_API_KEY'),
            ],
        ],
    ],
];

```

**Comment by alexw23** [comment]
There's a paypal express example here:

https://github.com/ignited/laravel-omnipay#paypal-express-example

Otherwise your issue should be reposted in https://github.com/thephpleague/omnipay-paypal as it's unrelated to laravel-omnipay.
