### ISSUE TITLE
Omnipay, PayPal - sandbox account, refund can not work

### ISSUE THREAD

**Issue by zzlajo** [ignited/laravel-omnipay#28]
I added omnipay packet to my laravel project. Customer have two way for paying on PayPal service. One way for paying is Credit Card for that used PayPal_Pro, second way is PayPal_Express.
I used a test account, a sandbox PayPal account.
I need to used refund, this method back money to customers. 
When I try refund i get error:

"You can not refund this type of transaction"

Anyone can help me?

**Can I use refund method on sandbox PayPal account?**

**Comment by alexw23** [comment]
There's a paypal express example here:

https://github.com/ignited/laravel-omnipay#paypal-express-example

Otherwise your issue should be reposted in https://github.com/thephpleague/omnipay-paypal as it's unrelated to laravel-omnipay.
