### ISSUE TITLE
Unable to upgrade to Laravel 5.3

### ISSUE THREAD

**Issue by bkuhl** [ignited/laravel-omnipay#29]
Can `"omnipay/common": "2.3.*"` be updated from `2.3.*` to `2.5.*`?

I'm unable to upgrade my application to 5.3 because of dependency version conflicts between the common library and Laravel for `symfony/http-foundation`.  I believe updating this dependency will resolve the issue.

**Comment by ImJustToNy** [comment]
I have the same issue :/

**Comment by quiquegarcia** [comment]
You need to put explicitly ```"ignited/laravel-omnipay": "2.*"``` in your composer.json or use ```composer require ignited/laravel-omnipay:2.*``` command, this way the package will use omnipay-common version 2.3 instead of 2.0

That worked for me, regards.

**Comment by alexw23** [comment]
https://github.com/ignited/laravel-omnipay/releases/tag/2.2.0 should fix it

**Comment by bkuhl** [comment]
Thanks!
