### ISSUE TITLE
Syntax does not support

### ISSUE THREAD

**Issue by BhagiLimbu** [ignited/laravel-omnipay#38]
I wonder if you have any proper sample documentation. I am new ominpay and using your library doesn't help. Most of the syntax does not support like Omnipay::creditCard etc...

**Comment by BhagiLimbu** [comment]
Appreciate if you could update a document, I use this way to get instances 

$oInstance = app()->make('omnipay');
$gateway = $oInstance->gateway('paypal'); // read configuration file (laravel-omnipay)

**Comment by isneezy** [comment]
Check this out https://github.com/ignited/laravel-omnipay#paypal-express-example
