### ISSUE TITLE
Switch to OmniPay ^3

### ISSUE THREAD

**Issue by johannesschobel** [ignited/laravel-omnipay#40]
Hey @alexw23 and community,
thanks for your plugin - looks really great!

I am trying to switch to OmniPay, and found this package here.. After reading the `composer.json` file, i found, that you are using omnipay 2.5 but 3.x is already available.

Is it possible to switch to 3.x?

**Comment by alexw23** [comment]
This package is using Omnipay 3.0 now. Switch to the "~3" of this package
