### ISSUE TITLE
WechatPay_Mweb  undefined

### ISSUE THREAD

**Issue by 791487145** [ignited/laravel-omnipay#45]
![default](https://user-images.githubusercontent.com/24927832/33697460-0cdc3c56-db42-11e7-9544-d657d3682772.png)

**Comment by wslsq** [comment]
WechatPay_Mweb应该写在driver里
![image](https://user-images.githubusercontent.com/12254744/41404619-44d26b06-6ffa-11e8-8eeb-d96b4c891dfb.png)

**Comment by 791487145** [comment]
嗯嗯，后来发现是这个问题，谢谢啦
