### ISSUE TITLE
Won't install in laravel 5.6

### ISSUE THREAD

**Issue by mitajunior** [ignited/laravel-omnipay#46]
Having trouble installing in laravel 5.6

**Comment by laijingwu** [comment]
+1

**Comment by deividaspetraitis** [comment]
+1, any updates?

**Comment by tanakornart** [comment]
I can't update to laravel 5.6

**Comment by alexw23** [comment]
Any idea on the errors you are having?

**Comment by alexw23** [comment]
I've successfully installed this on 5.3, 5.4, 5.5, 5.6, and 5.7. If you have any specific errors please post.
