### ISSUE TITLE
why  php-http/guzzle6-adapter back to  v1

### ISSUE THREAD

**Issue by liyu001989** [ignited/laravel-omnipay#50]
https://github.com/ignited/laravel-omnipay/commit/55f1fd3d5e72dcde045b0b11deb0130ef5744bea#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780

why  php-http/guzzle6-adapter back to  v1,   some other package use v2。

maybe should use `^1.1|^2`  ？

https://github.com/thephpleague/omnipay/commit/9e10d91cbf84744207e13d4483e79de39b133368

**Comment by alexw23** [comment]
Happy to accept any PRs
