### ISSUE TITLE
Upgrade laravel

### ISSUE THREAD

**Issue by PTNOP** [ignited/laravel-omnipay#52]
Hello the omipay dosen't supprot laravel 6.0.* Omipay will be upgrade to support laravel 6.0?

I have open a question on stackoverflow and some users have say the error is because omipay is not ready to laravel 6.0, i am sorry i don't understand alot of this i am just tring upgrade my system.

Can ypu check the link. Thanks in advance

https://stackoverflow.com/questions/57796599/laravel-6-0-composer-dependency-upgrade-error

**Comment by shalawani** [comment]
Any news about ugrade to Laravel 6

**Comment by PTNOP** [comment]
No :(

**Comment by isneezy** [comment]
@PTNOP @shalawani this is just a wrapper library. it is easy to make it support laravel 6 but we need to know if this repo is still active so we can make a PR for that

**Comment by PTNOP** [comment]
For me you can close if you tell me how I can make this support laravel 6 thanks in advance

**Comment by PTNOP** [comment]
Can anyone tell my how can i upgrade this? Thanks in advance

**Comment by alexw23** [comment]
Laravel 6 has been supported for a while now :)
