### ISSUE TITLE
Error Installing via Composer

### ISSUE THREAD

**Issue by PV-Patrick** [ignited/laravel-omnipay#9]
The install on this isn't working as of late, here is the error I am receiving after trying to install via composer.  Any idea on what the cause could be? Thank you!

Updating dependencies (including require-dev)
- Installing omnipay/common (v2.3.0)
  Downloading: connection...Failed to download omnipay/common from dist: The "
  https://api.github.com/repos/omnipay/common/zipball/f7d50ce82f3528e7402500d87223
  91ebb69070b8" file could not be downloaded (HTTP/1.1 404 Not Found)
  Now trying to download from source
- Installing omnipay/common (v2.3.0)
  Cloning f7d50ce82f3528e7402500d8722391ebb69070b8
  
  [RuntimeException]
  Failed to clone git@github.com:omnipay/common.git, git was not found, check
  that it is installed and in your PATH env.
  'git' is not recognized as an internal or external command,
  operable program or batch file.

**Comment by danhunsaker** [comment]
It explicitly says `git was not found, check that it is installed and in your PATH env` in that error message.  If you don't have `git` installed, Composer can't fall back to it if/when it has problems getting the ZIP file from GitHub (happens sometimes when GH hasn't created one yet, or when it doesn't have one for the specific commit Composer is looking for).  This isn't a bug with Composer *or* `laravel-omnipay`.

Either way, if your problem is resolved, go ahead and close this issue.  :)

**Comment by kyogenex** [comment]
I encountered this issue. What is the fix for this?

    Downloading: connection...Failed to download omnipay/targetpay from dist: The "https://api.github.com/repos/omnipay/targetpay/zipball/7274721c97f6f8ad3d2a8b4dea474ac548c45bac" file could not be downloaded (HTTP/1.1 404 Not Found)

**Comment by alexw23** [comment]
I'm not quite sure - you'd need to post that on omnipay as an issue.

**Comment by danhunsaker** [comment]
@kyogenex - Did it successfully install `omnipay/targetpay` via git in the next few lines?  

The error shown here simply means it couldn't find the ZIP file on GitHub's web servers, which itself probably just means they (GitHub, not Omnipay) haven't created the ZIP file yet.  That's one of the reasons Composer falls back to a `git clone` if the ZIP download fails.  Check that and let us know.

**Comment by kyogenex** [comment]
@danhunsaker 
@alexw23 

Thanks for the immediate response. I opened the composer.lock file in the project and found some of the links there are not anymore updated, from "omnipay/targetpay" is now "thephpleague/omnipay-targetpay" so with other plugins such as stripe, pin, etc.

**Comment by danhunsaker** [comment]
Ah.  A `composer update` will catch most of those, especially if you have `omnipay/omnipay` in your `composer.json`...
